
# (c) Secure Identity Alliance

openapi: 3.0.0
info:
  description: OSIA CMS Interface
  version: 1.0.0
  title: OSIA Credential Management System Interface
  license:
    name: SIA
    url: "https://raw.githubusercontent.com/SecureIdentityAlliance/osia/master/LICENSE"
tags:
  - name: Credential Request
servers:
  - url: http://cms.com/
  - url: https://cms.com/
paths:

  /v1/credentialRequest/person/{personId}:
    post:
      tags:
        - Credential Request
      summary: Create a request for a credential
      operationId: createCredentialRequest
      parameters:
        - name: personId
          in: path
          description: the id of the person to create the credential request for
          required: true
          schema:
            type: string
        - name: transactionId
          in: query
          description: The id of the transaction
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialRequest'
      responses:
        '201':
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialRequestId'
        '400':
          description: Bad request
        '403':
          description: Operation not allowed
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/credentialRequest/{credentialRequestId}:
    get:
      tags:
        - Credential Request
      summary: Read a credential request
      operationId: readCredentialRequest
      parameters:
        - name: credentialRequestId
          in: path
          description: the id of the credential request
          required: true
          schema:
            type: string
        - name: attributes
          in: query
          description: The (optional) set of attributes to retrieve
          required: false
          schema:
            type: array
            items:
              type: string
            example:
              - surname
              - familyname
        - name: transactionId
          in: query
          description: The id of the transaction
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Read successful
          $ref: '#/components/responses/CredentialRequestResponse'
        '400':
          description: Bad request
        '403':
          description: Read not allowed
        '404':
          description: Unknown record
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      tags:
        - Credential Request
      summary: Update a credential request
      operationId: updateCredentialRequest
      parameters:
        - name: credentialRequestId
          in: path
          description: the id of the credential request
          required: true
          schema:
            type: string
        - name: transactionId
          in: query
          description: The id of the transaction
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialRequest'
      responses:
        '204':
          description: Update successful
        '400':
          description: Bad request
        '403':
          description: Update not allowed
        '404':
          description: Unknown record
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Credential Request
      summary: Delete a credential request
      operationId: deleteCredentialRequest
      parameters:
        - name: credentialRequestId
          in: path
          description: the id of the credential request
          required: true
          schema:
            type: string
        - name: transactionId
          in: query
          description: The id of the transaction
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Delete successful
        '400':
          description: Bad request
        '403':
          description: Delete not allowed
        '404':
          description: Unknown record
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/credential:
    get:
      tags:
        - Credential
      summary: Retrieve a list of credentials that match the passed in search criteria
      operationId: findCredentials
      parameters:
        - name: expressions
          in: query
          description: The expressions to evaluate. Each expression
            is described with the attribute's name, the operator
            (one of ``<``, ``>``, ``=``, ``>=``, ``<=``)
            and the attribute value.
          required: true
          schema:
            $ref: '#/components/schemas/Expressions'
        - name: attributes
          in: query
          description: The (optional) set of required attributes to retrieve
          required: false
          schema:
            type: array
            items:
              type: string
        - name: transactionId
          in: query
          description: The id of the transaction
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Read successful
          $ref: '#/components/responses/CredentialResponse'
        '400':
          description: Bad request
        '403':
          description: Read not allowed
        '404':
          description: Unknown record
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/credential/{credentialId}:
    get:
      tags:
        - Credential
      summary: Read a credential
      operationId: readCredential
      parameters:
        - name: credentialId
          in: path
          description: the id of the credential
          required: true
          schema:
            type: string
        - name: attributes
          in: query
          description: The (optional) set of required attributes to retrieve
          required: false
          schema:
            type: array
            items:
              type: string
        - name: transactionId
          in: query
          description: The id of the transaction
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Read successful
          $ref: '#/components/responses/CredentialResponse'
        '400':
          description: Bad request
        '403':
          description: Read not allowed
        '404':
          description: Unknown record
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Credential
      summary: Cancel a credential
      operationId: cancelCredential
      parameters:
        - name: credentialId
          in: path
          description: the id of the credential
          required: true
          schema:
            type: string
        - name: transactionId
          in: query
          description: The id of the transaction
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Delete successful
        '400':
          description: Bad request
        '403':
          description: Delete not allowed
        '404':
          description: Unknown record
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/credential/{credentialId}/suspend:
    patch:
      tags:
        - Credential
      summary: (Un)suspend a credential
      operationId: suspendCredential, unsuspendCredential
      parameters:
        - name: credentialId
          in: path
          description: the id of the credential
          required: true
          schema:
            type: string
        - name: transactionId
          in: query
          description: The id of the transaction
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SuspendCredential'
      responses:
        '204':
          description: Update successful
        '400':
          description: Bad request
        '403':
          description: Update not allowed
        '404':
          description: Unknown record
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  responses:
    CredentialRequestResponse:
      description: The response for a credential request
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/CredentialRequestId'
              - $ref: '#/components/schemas/PersonId'
              - $ref: '#/components/schemas/CredentialRequest'      

    CredentialResponse:
      description: The response for a credential request
      content:
        application/json:
          schema:
            allOf:
              - $ref: '#/components/schemas/CredentialId'
              - $ref: '#/components/schemas/PersonId'
              - $ref: '#/components/schemas/Credential'

  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          description: Error code
          type: integer
          format: int32
        message:
          description: Error message
          type: string

    PersonId:
        type: object
        properties:
          personId:
            type: string
            description: The unique id of person that the credential request is for

    CredentialRequestId:
      type: object
      properties:
        credentialRequestId:
          type: string
          description: The unique id of this credential request

    CredentialRequest:
      description: A request for a credential
      type: object
      properties:
        credentialProfileId:
          type: string
          description: The id of the credential profile to request
        validFromDate:
          type: string
          format: date-time
          description: May be used to override the default start date of the
            requested credential.  This must only be later than the current
            date, not earlier.
        validToDate:
          type: string
          format: date-time
          description: May be used to override the default expiry date of the
            requested credential.  This must only be earlier than the default
            expiry, not later.
      required:
        - credentialProfileId

    CredentialId:
      type: object
      properties:
        credentialId:
          type: string
          description: The unique id for this credential

    Credential:
      description: A credential
      type: object
      properties:
        issuedDate:
          type: string
          format: date-time
          description: The date that this credential was issued
        expiryDate:
          type: string
          format: date-time
          description: The date that this credential expires
        suspended:
          type: boolean
          description: Is this credential suspended
          default: false
        cancelled:
          type: boolean
          description: Is this credential cancelled
          default: false
      required:
        - credentialId

    SuspendCredential:
      type: object
      properties:
        suspended:
          type: boolean
        reason:
          type: string
          description: the reason for (un)suspension


    Expression:
      type: object
      required:
        - attributeName
        - operator
        - value
      properties:
        attributeName:
          type: string
        operator:
          type: string
          enum: ['<', '>', '=', '>=', '<=', '!=']
        value:
          oneOf:
          - type: string
          - type: integer
          - type: number
          - type: boolean
    Expressions:
      type: array
      items:
        $ref: '#/components/schemas/Expression'
        
