
# (c) Secure Identity Alliance

openapi: 3.0.0
info:
  description: OSIA Enrollment Interface
  version: 1.1.0
  title: OSIA Enrollment Interface
  license:
    name: SIA
    url: "https://raw.githubusercontent.com/SecureIdentityAlliance/osia/master/LICENSE"
tags:
  - name: Enrollment
servers:
  - url: http://enrollment.com/
  - url: https://enrollment.com/
paths:

  /v1/enrollment/{enrollmentId}:
    post:
      tags:
        - Enrollment
      summary: Create one enrollment
      operationId: createEnrollment
      parameters:
        - name: enrollmentId
          in: path
          description: the id of the enrollment
          required: true
          schema:
            type: string
        - name: transactionId
          in: query
          description: The id of the transaction
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Enrollment'
      responses:
        '201':
          description: Operation successful
        '400':
          description: Bad request
        '403':
          description: Operation not allowed
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      tags:
        - Enrollment
      summary: Read one enrollment
      operationId: readEnrollment
      parameters:
        - name: enrollmentId
          in: path
          description: the id of the enrollment
          required: true
          schema:
            type: string
        - name: transactionId
          in: query
          description: The id of the transaction
          required: true
          schema:
            type: string
        - name: attributes
          in: query
          description: The (optional) set of required attributes to retrieve
          required: false
          schema:
            type: array
            items:
              type: string
            example:
              - surname
              - familyname
      responses:
        '200':
          description: Read successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Enrollment'
        '400':
          description: Bad request
        '403':
          description: Read not allowed
        '404':
          description: Unknown record
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - enrollment
      summary: Update one enrollment
      operationId: updateEnrollment
      parameters:
        - name: enrollmentId
          in: path
          description: the id of the enrollment
          required: true
          schema:
            type: string
        - name: transactionId
          in: query
          description: The id of the transaction
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Enrollment'
      responses:
        '204':
          description: Update successful
        '400':
          description: Bad request
        '403':
          description: Update not allowed
        '404':
          description: Unknown record
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Enrollment
      summary: Delete an enrollment
      operationId: deleteEnrollment
      parameters:
        - name: enrollmentId
          in: path
          description: the id of the enrollment
          required: true
          schema:
            type: string
        - name: transactionId
          in: query
          description: The id of the transaction
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Delete successful
        '400':
          description: Bad request
        '403':
          description: Delete not allowed
        '404':
          description: Unknown record
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /v1/enrollments:
    get:
      tags:
        - Enrollment
      summary: Retrieve a list of enrollments which match passed in search criteria
      operationId: findEnrollments
      parameters:
        - name: expressions
          in: query
          description: The expressions to evaluate.
          required: true
          schema:
            $ref: '#/components/schemas/Expressions'
        - name: transactionId
          in: query
          description: The id of the transaction
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Read successful
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/Enrollment'
        '400':
          description: Bad request
        '403':
          description: Read not allowed
        '404':
          description: Unknown record
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          description: Error code
          type: integer
          format: int32
        message:
          description: Error message
          type: string
    Enrollment:
      description: >-
        Enrollment entity.
      type: object
      required:
        - enrollmentTypeId
      properties:
        enrollmentId:
          type: string
          description: The unique id for this enrollment
        enrollmentTypeId:
          type: string
          description: The enrollment type id for this enrollment
    Expression:
      type: object
      required:
        - attributeName
        - operator
        - value
      properties:
        attributeName:
          type: string
        operator:
          type: string
          enum: ['<', '>', '=', '>=', '<=']
        value:
          oneOf:
          - type: string
          - type: integer
          - type: number
          - type: boolean
    Expressions:
      type: array
      items:
        $ref: '#/components/schemas/Expression'
   
